### ISSUE TITLE
Update "Getting started" to reflect file changes

### ISSUE THREAD

**Issue by emigenix** [watson-developer-cloud/conversational-agent#20]
Please update the instructions under *Getting started* header. In particular item 6 for editing the `manifest.yml` file. In latest clone it look like this: 

```yml
---
declared-services:
  dialog-service:
    label: dialog
    plan: standard
  natural-language-classifier-standard:
    label: natural_language_classifier
    plan: standard
applications:
- services:
  - dialog-service
  - natural-language-classifier-standard
  name: conversational-agent-application-starter-kit
  command: npm start
  path: .
  memory: 512M
```
